name: Submit Suggestion
description: If you have any suggestions for the downloader, you can submit them here in English.
labels: [ "enhancement" ]
body:
  - type: checkboxes
    id: "yml-0"
    attributes:
      label: "Checklist"
      description: "Please check the following items one by one and tick them to confirm."
      options:
        - label: "I confirm that this issue has not been addressed in the latest version of the downloader"
          required: true
        - label: "I confirm that there are no other identical suggestions in Issues"
          required: true
        - label: "If you have tried the latest dev version of the code, please select this option"
        - label: "the issue still persists in the latest dev version"
  - type: textarea
    id: "yml-1"
    attributes:
      label: Desired Feature
      placeholder: "- (Please answer here) -"
    validations:
      required: true
  - type: textarea
    id: "yml-2"
    attributes:
      label: Downloader Version You Are Using
      placeholder: "- (Please answer here) -"
  - type: textarea
    id: "yml-6"
    attributes:
      label: If you are still able to open the downloader to export information, please provide the relevant file here
      placeholder: "-(Please upload files here)-"
  - type: textarea
    id: "yml-4"
    attributes:
      label: Other Supplementary Information
      placeholder: "- (Please answer here) -"
